name: main.yml

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.9.0
    steps:
    - uses: actions/checkout@v3
    - name: Run shellcheck
      run: shellcheck -s bash -f tty *

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d *
